# Clone the git repo.
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/cluster-testing:$SHORT_SHA'
  - '.'
# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/cluster-testing:$SHORT_SHA'

- id: 'deploy to gke'
  name: 'gcr.io/cloud-builders/gcloud'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-test'
    - 'KUBECONFIG=/.kube/config'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
          gcloud container clusters get-credentials cluster-test --project datalabs-hs --zone us-central1-c	
          sed -i 's|gcr.io/project-id/cluster-testing|gcr.io/$PROJECT_ID/cluster-testing:$SHORT_SHA|' ./deployment.yaml
          cat deployment.yaml
          kubectl apply -f ./deployment.yaml
timeout: 2000s